#!/usr/bin/env bash
# Integrated cluster + monitoring setup
# Creates a local Valkey cluster and sets up redis-exporter → Prometheus → Grafana pipeline
#
# Usage:
#   ./create_cluster_monitoring.sh /path/to/valkey start
#   ./create_cluster_monitoring.sh /path/to/valkey create
#   ./create_cluster_monitoring.sh stop
#   ./create_cluster_monitoring.sh status
#   ./create_cluster_monitoring.sh clean

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
SETUP_CLUSTER_DIR="$(cd -- "$SCRIPT_DIR/../setup_cluster" && pwd)"
CLUSTER_CONFIG="${CLUSTER_CONFIG:-$SETUP_CLUSTER_DIR/cluster_config.sh}"

# Source cluster configuration
if [[ ! -f "$CLUSTER_CONFIG" ]]; then
  echo "error: cluster config not found: $CLUSTER_CONFIG" >&2
  exit 1
fi
# shellcheck source=../setup_cluster/cluster_config.sh
source "$CLUSTER_CONFIG"

# Monitoring configuration
EXPORTER_BASE_PORT="${EXPORTER_BASE_PORT:-9200}"  # Exporters at 9200-9205 (one per node)
PROMETHEUS_PORT="${PROMETHEUS_PORT:-9090}"
GRAFANA_PORT="${GRAFANA_PORT:-3000}"
MONITORING_DATA_DIR="${MONITORING_DATA_DIR:-$SCRIPT_DIR/config}"

VALKEY_DIR="${VALKEY_DIR:-}"
CMD="${1:-}"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
  echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $*" >&2
}

usage() {
  cat <<EOF
Usage:
  $(basename "$0") [<valkey-dir>] <start|create|stop|restart|clean|status>

Commands:
  start    - Start Valkey cluster and monitoring (exporters, Prometheus, Grafana)
  create   - Create Valkey cluster (after start)
  stop     - Stop all services
  restart  - Stop and start all services
  clean    - Remove all data and Docker containers
  status   - Check cluster and services status

<valkey-dir> must contain built Valkey binaries (src/valkey-server, src/valkey-cli).

Configuration (cluster_config.sh):
  CLUSTER_HOST=${CLUSTER_HOST}, BASE_PORT=${BASE_PORT}, NUM_NODES=${NUM_NODES}

Monitoring Services:
  Redis Exporters: localhost:${EXPORTER_BASE_PORT}-$((EXPORTER_BASE_PORT + NUM_NODES - 1))
  Prometheus:      localhost:${PROMETHEUS_PORT}
  Grafana:         localhost:${GRAFANA_PORT}

Environment:
  VALKEY_DIR, CLUSTER_CONFIG, CLUSTER_DATA_DIR, EXPORTER_BASE_PORT, PROMETHEUS_PORT, GRAFANA_PORT

EOF
}

if [[ -z "$CMD" ]]; then
  usage
  exit 1
fi

# Detect VALKEY_DIR if passed as argument
if [[ -n "${1:-}" && -d "$1" && -x "$1/src/valkey-server" ]]; then
  VALKEY_DIR="$(cd -- "$1" && pwd)"
  CMD="${2:-}"
  if [[ -z "$CMD" ]]; then
    usage
    exit 1
  fi
fi

# Validate VALKEY_DIR for cluster operations
case "$CMD" in
  start|create|restart)
    VALKEY_DIR="${VALKEY_DIR:-}"
    if [[ -z "$VALKEY_DIR" ]]; then
      log_error "set VALKEY_DIR or pass <valkey-dir> as the first argument"
      usage
      exit 1
    fi
    if [[ ! -x "$VALKEY_DIR/src/valkey-server" ]]; then
      log_error "missing or not executable: $VALKEY_DIR/src/valkey-server"
      exit 1
    fi
    ;;
esac

mkdir -p "$MONITORING_DATA_DIR"
MONITORING_DATA_DIR="$(cd -- "$MONITORING_DATA_DIR" && pwd)"

# Create Docker network if it doesn't exist
create_docker_network() {
  if ! docker network ls --format '{{.Name}}' | grep -q "^valkey-monitoring$"; then
    log_info "Creating Docker network: valkey-monitoring"
    docker network create valkey-monitoring 2>/dev/null || log_warn "Network may already exist"
  fi
}

# Generate Prometheus configuration
generate_prometheus_config() {
  local config_file="$MONITORING_DATA_DIR/prometheus.yml"
  local last_exporter_port=$((EXPORTER_BASE_PORT + NUM_NODES - 1))
  
  mkdir -p "$MONITORING_DATA_DIR"
  cat >"$config_file" <<PROM_EOF
# Prometheus Configuration
# Generated by: setup_monitoring/create_cluster_monitoring.sh
# 
# Prometheus Server:
#   - Port: $PROMETHEUS_PORT
#   - Access: http://localhost:$PROMETHEUS_PORT
#   - Targets below are scraped every 15 seconds

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
PROM_EOF

  # Add each redis-exporter as a target
  for ((i = 0; i < NUM_NODES; i++)); do
    local exporter_port=$((EXPORTER_BASE_PORT + i))
    local node_port=$((BASE_PORT + i))
    cat >>"$config_file" <<PROM_CONF
  - job_name: "redis_node_${node_port}"
    static_configs:
      - targets: ["host.docker.internal:${exporter_port}"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "redis_${node_port}"
PROM_CONF
  done

  log_info "Generated Prometheus config: $config_file"
}

# Start redis-exporter for each cluster node
start_exporters() {
  local port
  log_info "Starting redis-exporters..."
  create_docker_network
  
  for ((i = 0; i < NUM_NODES; i++)); do
    local exporter_port=$((EXPORTER_BASE_PORT + i))
    local node_port=$((BASE_PORT + i))
    local container_name="redis-exporter-$node_port"
    
    # Check if container exists
    if docker ps -a --format '{{.Names}}' | grep -q "^${container_name}$"; then
      docker rm -f "$container_name" 2>/dev/null || true
    fi
    
    log_info "Starting $container_name (redis $CLUSTER_HOST:$node_port -> exporter :$exporter_port)"
    docker run -d \
      --name "$container_name" \
      --network valkey-monitoring \
      -p "$exporter_port:9121" \
      oliver006/redis_exporter:latest \
      -redis.addr="host.docker.internal:$node_port" \
      -redis.password="" \
      2>/dev/null || log_warn "Failed to start $container_name (is redis running on port $node_port?)"
  done
}

# Stop redis-exporters
stop_exporters() {
  log_info "Stopping redis-exporters..."
  for ((i = 0; i < NUM_NODES; i++)); do
    local node_port=$((BASE_PORT + i))
    local container_name="redis-exporter-$node_port"
    docker rm -f "$container_name" 2>/dev/null || true
  done
}

# Start Prometheus
start_prometheus() {
  local container_name="prometheus"
  
  log_info "Starting Prometheus..."
  create_docker_network
  
  # Remove old container if exists
  docker rm -f "$container_name" 2>/dev/null || true
  
  # Generate fresh config
  generate_prometheus_config
  
  docker run -d \
    --name "$container_name" \
    --network valkey-monitoring \
    -p "$PROMETHEUS_PORT:9090" \
    -v "$MONITORING_DATA_DIR/prometheus.yml:/etc/prometheus/prometheus.yml:ro" \
    prom/prometheus:latest \
    --config.file=/etc/prometheus/prometheus.yml \
    --storage.tsdb.path=/prometheus \
    2>/dev/null || log_error "Failed to start Prometheus"
}

# Stop Prometheus
stop_prometheus() {
  log_info "Stopping Prometheus..."
  docker rm -f prometheus 2>/dev/null || true
}

# Start Grafana
start_grafana() {
  local container_name="grafana"
  
  log_info "Starting Grafana..."
  create_docker_network
  
  # Remove old container if exists
  docker rm -f "$container_name" 2>/dev/null || true
  
  # Ensure provisioning directories exist
  mkdir -p "$MONITORING_DATA_DIR/provisioning/datasources"
  mkdir -p "$MONITORING_DATA_DIR/provisioning/dashboards"
  
  docker run -d \
    --name "$container_name" \
    --network valkey-monitoring \
    -p "$GRAFANA_PORT:3000" \
    -e "GF_SECURITY_ADMIN_USER=admin" \
    -e "GF_SECURITY_ADMIN_PASSWORD=admin" \
    -e "GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=true" \
    -e "GF_AUTH_ANONYMOUS_ENABLED=true" \
    -e "GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer" \
    -e "GF_USERS_ALLOW_SIGN_UP=false" \
    -v "$MONITORING_DATA_DIR/grafana.ini:/etc/grafana/grafana.ini:ro" \
    -v "$MONITORING_DATA_DIR/provisioning/datasources:/etc/grafana/provisioning/datasources:ro" \
    -v "$MONITORING_DATA_DIR/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro" \
    grafana/grafana:latest \
    2>/dev/null || log_error "Failed to start Grafana"
}

# Stop Grafana
stop_grafana() {
  log_info "Stopping Grafana..."
  docker rm -f grafana 2>/dev/null || true
}

# Check services status
check_status() {
  log_info "Checking cluster status..."
  
  local cluster_cli="$VALKEY_DIR/src/valkey-cli"
  if [[ -x "$cluster_cli" ]]; then
    "$cluster_cli" -h "$CLUSTER_HOST" -p "$BASE_PORT" cluster info 2>/dev/null || \
      log_warn "Cluster not responding on $CLUSTER_HOST:$BASE_PORT"
  else
    log_warn "valkey-cli not found; skipping cluster check"
  fi
  
  log_info "Docker containers:"
  docker ps --filter "name=redis-exporter|prometheus|grafana" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" || true
  
  log_info "Service URLs:"
  echo "  Prometheus:    http://localhost:$PROMETHEUS_PORT"
  echo "  Grafana:       http://localhost:$GRAFANA_PORT (admin/admin)"
  echo "  Cluster:       $CLUSTER_HOST:$BASE_PORT (use valkey-cli)"
}

# Delegate to cluster setup script
delegate_to_cluster() {
  local cluster_cmd="$1"
  shift
  
  log_info "Delegating to setup_cluster..."
  cd "$SETUP_CLUSTER_DIR"
  
  case "$cluster_cmd" in
    start)
      ./create_valkey_cluster.sh "$VALKEY_DIR" start
      ;;
    create)
      ./create_valkey_cluster.sh "$VALKEY_DIR" create
      ;;
    stop)
      ./create_valkey_cluster.sh "$VALKEY_DIR" stop
      ;;
    restart)
      ./create_valkey_cluster.sh "$VALKEY_DIR" restart
      ;;
    clean)
      ./create_valkey_cluster.sh "$VALKEY_DIR" clean
      ;;
    *)
      log_error "Unknown cluster command: $cluster_cmd"
      exit 1
      ;;
  esac
}

# Main command dispatch
case "$CMD" in
  start)
    log_info "Starting integrated cluster + monitoring..."
    delegate_to_cluster "start"
    sleep 2
    start_exporters
    sleep 2
    start_prometheus
    sleep 2
    start_grafana
    sleep 2
    check_status
    log_info "All services started!"
    log_info ""
    log_info "Next steps:"
    log_info "1. Create the cluster: $(basename "$0") $VALKEY_DIR create"
    log_info "2. Access Prometheus: http://localhost:$PROMETHEUS_PORT"
    log_info "3. Access Grafana: http://localhost:$GRAFANA_PORT (admin/admin)"
    log_info ""
    log_info "To add a Prometheus datasource in Grafana:"
    log_info "  - Go to Connections > Data sources"
    log_info "  - Click 'Add data source' and select 'Prometheus'"
    log_info "  - URL: http://localhost:$PROMETHEUS_PORT"
    log_info "  - Save & test"
    ;;
  create)
    log_info "Creating cluster..."
    delegate_to_cluster "create"
    check_status
    ;;
  stop)
    log_info "Stopping all services..."
    delegate_to_cluster "stop"
    stop_exporters
    stop_prometheus
    stop_grafana
    log_info "All services stopped"
    ;;
  restart)
    log_info "Restarting all services..."
    delegate_to_cluster "restart"
    sleep 2
    stop_exporters
    start_exporters
    sleep 2
    start_prometheus
    check_status
    ;;
  clean)
    log_info "Cleaning up all data and containers..."
    delegate_to_cluster "stop"
    delegate_to_cluster "clean"
    stop_exporters
    stop_prometheus
    stop_grafana
    rm -rf "$MONITORING_DATA_DIR"
    log_info "Cleanup complete"
    ;;
  status)
    check_status
    ;;
  *)
    log_error "Unknown command: $CMD"
    usage
    exit 1
    ;;
esac